# Generated by Django 3.1.1 on 2020-10-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='tech_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
