# Generated by Django 3.1.1 on 2020-10-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_technology_tech_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='tech_type',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
