# Generated by Django 3.1.1 on 2020-10-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_newsupdates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
