# Generated by Django 3.1.1 on 2020-10-15 16:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='msg',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
