# Generated by Django 3.1.1 on 2020-10-16 15:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20201015_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsupdates',
            name='news_desc_1',
        ),
        migrations.RemoveField(
            model_name='newsupdates',
            name='news_desc_2',
        ),
        migrations.AddField(
            model_name='newsupdates',
            name='news_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
