# Generated by Django 3.1.1 on 2020-10-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20201016_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Doubt',
            fields=[
                ('doubt_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1500)),
                ('doubt_content', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
