# Generated by Django 3.1.1 on 2020-12-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_post_doubt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='f_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='l_name',
        ),
    ]
