# Generated by Django 3.1.1 on 2020-12-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20201201_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('header_img', models.ImageField(upload_to='')),
                ('course_image', models.ImageField(upload_to='')),
                ('atc', models.TextField()),
                ('skills', models.TextField()),
                ('wywl_1', models.TextField()),
                ('wywl_2', models.TextField()),
                ('wywl_3', models.TextField()),
                ('wywl_4', models.TextField()),
            ],
        ),
    ]
