# Generated by Django 3.1.1 on 2020-12-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='wywl_1',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='wywl_2',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='wywl_3',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='wywl_4',
        ),
        migrations.AddField(
            model_name='courses',
            name='certificate',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
