# Generated by Django 3.1.1 on 2020-12-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20201211_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='certificate',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
