# Generated by Django 3.1.1 on 2020-12-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20201211_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrollments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=1000)),
                ('time_stamp', models.CharField(max_length=30)),
            ],
        ),
    ]
