# Generated by Django 3.1.1 on 2020-12-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_enrollments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notice',
            new_name='Blog',
        ),
    ]
