# Generated by Django 3.1.1 on 2020-12-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20201219_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='msg',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='subject',
            new_name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
