# Generated by Django 3.1.1 on 2020-12-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_auto_20201219_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='whatsapp_group_link',
            field=models.URLField(null=True),
        ),
    ]
