# Generated by Django 3.1.1 on 2020-12-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_courses_whatsapp_group_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='whatsapp_group_link',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
