# Generated by Django 3.1.1 on 2020-12-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_auto_20201224_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='whatsapp_group_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
