# Generated by Django 3.1.1 on 2021-01-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_auto_20201224_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('course', models.CharField(max_length=200)),
                ('msg', models.TextField()),
                ('status', models.CharField(default=False, max_length=20)),
            ],
        ),
    ]
