# Generated by Django 3.1.1 on 2021-01-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_auto_20210120_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
