# Generated by Django 3.1.1 on 2021-01-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(default='Reject', max_length=20),
        ),
    ]
