# Generated by Django 3.1.5 on 2021-01-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_auto_20210121_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship_Enrollments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('internship', models.CharField(max_length=200)),
            ],
        ),
    ]
