# Generated by Django 3.1.5 on 2021-01-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_internship_enrollments'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='core',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
